
application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production
  
server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  
logging:
  level: INFO
  format: json
  
development:
  enable: flase
  port: 3000
  hot_reload: false
  mock_apis: false
  debug_mode: false
enable_auto_restart: true